[package]
name = "kravl"
version = "0.1.0"
authors = ["nilq <i.am@nilq.dk>"]
description = "the kravl language - parser module"
license = "MIT/Apache-2.0"
homepage = "https://github.com/nilq/kravl"
repository = "https://github.com/nilq/kravl"

[dependencies]
kravl-parser = "*"